# Copyright(C) [2026] Advanced Micro Devices, Inc. All rights reserved.
"""Forge agent — bridges AgentKernelArena to KernelForge's `forge-loop`.

KernelForge's autonomous optimization loop (baseline -> agent edit -> 5-stage
validate -> bench -> keep/revert) runs as a standalone, hard-killable subprocess
via `kernel-agents forge-loop`. This launcher adapts an Arena task workspace to
that loop's contract:

  1. Resolve the kernel file Arena copied into the workspace (task's
     ``source_file_path[0]``).
  2. Materialize a driver shim implementing the KernelForge driver contract
     (prints ``SNR: <db> dB`` for correctness and ``wall_ms: <ms>`` for bench).
  3. ``git init`` + initial commit the workspace (the loop uses git keep/revert).
  4. Shell out to ``kernel-agents forge-loop`` (streaming output), which leaves
     the workspace at the best-kept kernel.

After this returns, Arena re-materializes its perf helpers and re-scores the
kernel with the task's own compile/correctness/performance commands.

Machinery shared with the ``forge_rewrite`` agent (GPU identity, git workspace,
subprocess streaming, result parsing) lives in ``common.py``; it is imported
here so this module stays the single import surface for the forge-loop path.
"""

from __future__ import annotations

import json
import logging
import shlex
import shutil
from pathlib import Path
from typing import Any

import yaml

from agents import register_agent
from agents.forge.common import (
    FORGE_RESULT_SENTINEL as _FORGE_RESULT_SENTINEL,
    FORGE_SHUTDOWN_MARGIN_SECONDS as _FORGE_SHUTDOWN_MARGIN_SECONDS,
    KB_STATUS_FILE as _KB_STATUS_FILE,
    _capture_forge_edit_baseline,
    _declared_editable_sources,
    _forge_max_hours,
    _git,
    _infer_backend,
    _init_git_workspace,
    _logical_operator,
    _normalize_logical_operator,
    _read_forge_result,
    _resolve_all_source_files,
    _resolve_fellow,
    _resolve_framework,
    _resolve_gpu_arch,
    _resolve_gpu_type,
    _resolve_kernel_file,
    _resolve_kernel_kind,
    _strip_nested_git,
    _task_kernel_identity,
    _terminate_process_group,
    _verify_forge_edit_scope,
    forge_environment,
    run_forge_subprocess,
)


def _render_driver_shim(drivers_dir: str, workspace: str, task_config: str, arena_root: str) -> str:
    """Generate a forge_driver.py that bakes the task paths in (no env needed).

    The shim adds the shared adapter's dir to sys.path and delegates to
    ``arena_task_adapter.run``, passing workspace / task config / arena root as
    explicit arguments. KernelForge invokes this file as ``python forge_driver.py
    <args>`` (see kernel_agents.mcp_server.tools.{test,bench}), so a ``__main__``
    entry is all that is required.
    """
    return f"""\
#!/usr/bin/env python3
# Auto-generated by the AgentKernelArena forge launcher. Task paths are baked in
# below so the driver needs NO environment variables. It delegates to the shared
# arena_task_adapter, which reuses Arena's own correctness/performance eval.
import sys

sys.path.insert(0, {drivers_dir!r})
import arena_task_adapter as adapter

WORKSPACE = {workspace!r}
TASK_CONFIG = {task_config!r}
ARENA_ROOT = {arena_root!r}

if __name__ == "__main__":
    raise SystemExit(adapter.run(WORKSPACE, TASK_CONFIG, ARENA_ROOT, sys.argv[1:]))
"""


def _build_forge_command(
    *,
    forge_bin: str,
    kernel_file: Path,
    driver_dest: Path,
    workspace: str,
    experiments_dir: Path,
    result_json: Path,
    agent_config: dict[str, Any],
    gpu_arch: str,
    gpu_type: str,
    fellow: str,
    task_type: str,
    source_files: list[Path],
    target_functions: list[str],
    logical_operator: str,
    framework: str,
) -> list[str]:
    """Build argv without shell parsing so task metadata is forwarded exactly."""
    cmd = [
        forge_bin,
        "forge-loop",
        "--kernel",
        str(kernel_file),
        "--driver",
        str(driver_dest),
        "--workspace",
        str(workspace),
        "--experiments-dir",
        str(experiments_dir),
        "--result-json",
        str(result_json),
        "--snr-threshold",
        str(agent_config.get("snr_threshold", 30.0)),
        "--max-iters",
        str(agent_config.get("max_iters", 2)),
        "--max-hours",
        str(_forge_max_hours(agent_config)),
        "--gpu-target",
        gpu_arch,
        "--gpu-type",
        gpu_type,
        "--fellow",
        fellow,
        "--git-branch",
        "forge-optimize",
        "--model",
        str(agent_config.get("model", "claude-opus-4-8")),
        "--permission-mode",
        str(agent_config.get("permission_mode", "acceptEdits")),
        "--task-type",
        task_type,
    ]
    if source_files:
        cmd.extend(["--source-files", ",".join(str(path) for path in source_files)])
    if target_functions:
        cmd.extend(["--target-functions", ",".join(str(name) for name in target_functions)])
    if logical_operator:
        cmd.extend(["--operator-name", logical_operator])
    if framework:
        cmd.extend(["--framework", framework])
    return cmd


def _publication_status(result: dict[str, Any] | None) -> dict[str, Any]:
    """Summarize optional remote publication diagnostics."""
    def _authoritative(publication: Any) -> bool:
        if not isinstance(publication, dict) or "published_commit" not in publication:
            return False
        return (
            "pending_commit" in publication
            or publication.get("status") == "warm_start_existing"
        )

    status: dict[str, Any] = {
        "published": False,
        "latest_best_published": False,
        "authoritative": False,
        "state": "result_missing" if result is None else "not_published",
        "reason": "",
        "best_commit": "",
        "published_commit": "",
        "pending_commit": "",
    }
    if result is None:
        status["reason"] = "forge_result_missing"
        return status

    best_commit = str(result.get("best_commit") or "")
    status["best_commit"] = best_commit
    top_level = result.get("remote_publication")
    publication = top_level if isinstance(top_level, dict) else None
    source = "remote_publication"
    kb_experience = result.get("kb_experience")
    top_level_authoritative = _authoritative(publication)
    if not top_level_authoritative and isinstance(kb_experience, dict):
        nested = kb_experience.get("publication")
        nested_authoritative = _authoritative(nested)
        if nested_authoritative or publication is None:
            publication = nested
            source = "kb_experience.publication"
    if publication is None:
        status["state"] = "schema_unsupported"
        status["reason"] = (
            "forge result has neither remote_publication nor "
            "kb_experience.publication"
        )
        return status

    status["source"] = source
    status["authoritative"] = _authoritative(publication)
    published_commit = str(publication.get("published_commit") or "")
    pending_commit = str(publication.get("pending_commit") or "")
    status["published_commit"] = published_commit
    status["pending_commit"] = pending_commit
    status["publication_state"] = str(publication.get("status") or "")
    latest_best_published = bool(
        status["authoritative"]
        and best_commit
        and published_commit == best_commit
        and not pending_commit
    )
    status["published"] = latest_best_published
    status["latest_best_published"] = latest_best_published
    status["state"] = (
        "published"
        if latest_best_published
        else str(publication.get("status") or "not_published")
    )
    if not best_commit:
        status["reason"] = "best_commit_missing"
    elif not status["authoritative"]:
        status["reason"] = "publication_schema_incomplete"
    elif pending_commit:
        status["reason"] = f"publication_pending:{pending_commit}"
    elif published_commit != best_commit:
        status["reason"] = (
            f"published_commit_mismatch:{published_commit or '<none>'}!={best_commit}"
        )

    if isinstance(kb_experience, dict):
        final_write = kb_experience.get("write")
        if isinstance(final_write, dict):
            status["final_write"] = {
                key: final_write[key]
                for key in ("written", "reason")
                if key in final_write
            }
    return status


def _write_forge_status(
    experiments_dir: Path,
    *,
    returncode: int | None,
    timed_out: bool,
    result: dict[str, Any] | None,
    kb_status: dict[str, Any],
) -> dict[str, Any]:
    summary = {
        "exit_code": returncode,
        "timed_out": timed_out,
        "kb": kb_status,
        "experiment_id": (result or {}).get("experiment_id", ""),
        "improved": bool((result or {}).get("improved", False)),
        "best_iteration": (result or {}).get("best_iteration", 0),
    }
    experiments_dir.mkdir(parents=True, exist_ok=True)
    (experiments_dir / _KB_STATUS_FILE).write_text(
        json.dumps(summary, indent=2, sort_keys=True)
    )
    return summary


@register_agent("forge")
def launch_agent(eval_config: dict[str, Any], task_config_dir: str, workspace: str) -> str:
    """Run one KernelForge forge-loop over the Arena task workspace.

    Args:
        eval_config: Arena run config (includes target_gpu_model).
        task_config_dir: Path to the task's config.yaml (for source/target fields).
        workspace: Isolated task workspace Arena prepared; the kernel lives here.

    Returns:
        Combined streamed output of the forge-loop subprocess.
    """
    logger = logging.getLogger(__name__)

    forge_bin = shutil.which("kernel-agents")
    if not forge_bin:
        raise RuntimeError(
            "Command 'kernel-agents' not found. Install KernelForge "
            "(pip install -e KernelForge) so the forge-loop CLI is on PATH."
        )

    # Agent config
    config_path = Path(__file__).with_name("agent_config.yaml")
    with config_path.open("r") as f:
        agent_config = yaml.safe_load(f) or {}

    # Task config: locate the kernel file + target function(s).
    with open(task_config_dir, "r") as f:
        task_config = yaml.safe_load(f) or {}
    identity_config = _task_kernel_identity(task_config)
    source_files = task_config.get("source_file_path") or []
    if not isinstance(source_files, list) or not source_files:
        raise RuntimeError(f"Task config has no source_file_path: {task_config_dir}")
    kernel_file = _resolve_kernel_file(workspace, source_files, task_config)
    editable_source_entries = _declared_editable_sources(task_config)
    # Resolve the complete edit allowlist. source_file_path[0] remains the anchor;
    # editable_sources adds dependent files without changing anchor semantics.
    all_source_files = _resolve_all_source_files(
        workspace,
        editable_source_entries,
        task_config,
        logger,
        strict=bool(identity_config),
    )
    target_funcs = task_config.get("target_kernel_functions") or []
    if not isinstance(target_funcs, list):
        raise ValueError("target_kernel_functions must be a list")
    target_funcs = [str(name).strip() for name in target_funcs if str(name).strip()]
    task_type = str(task_config.get("task_type") or "").strip()

    gpu_arch = _resolve_gpu_arch(eval_config)
    gpu_type = _resolve_gpu_type(eval_config)
    fellow = _resolve_fellow(task_config, agent_config)
    logical_operator = _logical_operator(task_config)
    kernel_kind = _resolve_kernel_kind(task_config)
    framework = _resolve_framework(task_config)

    env = forge_environment()

    # Materialize the driver: prefer a task-shipped scripts/forge_driver.py
    # (used verbatim); otherwise generate a shim that delegates to the shared
    # arena_task_adapter with the task paths baked in — so the driver needs NO
    # environment variables.
    arena_root = str(Path(__file__).resolve().parents[2])
    driver_dest = Path(workspace) / "forge_driver.py"
    task_driver = Path(workspace) / "scripts" / "forge_driver.py"
    if task_driver.exists():
        shutil.copy2(task_driver, driver_dest)
        logger.info(f"Forge: using task-provided driver {task_driver}")
    else:
        drivers_dir = str(Path(__file__).parent / "drivers")
        workspace_task_config = Path(workspace) / "config.yaml"
        task_config_path = str(
            workspace_task_config if workspace_task_config.exists() else task_config_dir
        )
        driver_dest.write_text(_render_driver_shim(
            drivers_dir=drivers_dir,
            workspace=str(workspace),
            task_config=task_config_path,
            arena_root=arena_root,
        ))
        logger.info(f"Forge: generated driver shim -> {driver_dest} (task paths baked in)")

    # Repository / image_kernel tasks bring a cloned repo (with its own nested
    # .git) into the workspace. Strip it before outer git init so keep/revert
    # tracks the real source files.
    if task_type.lower() in ("repository", "image_kernel"):
        _strip_nested_git(workspace, logger)

    # The loop needs a git repo for the keep/revert pattern.
    _init_git_workspace(workspace, logger)
    edit_baseline = _capture_forge_edit_baseline(workspace)

    experiments_dir = Path(workspace) / "forge_experiments"
    result_json = experiments_dir / "forge_result.json"
    result_json.unlink(missing_ok=True)

    model = str(agent_config.get("model", "claude-opus-4-8"))
    cmd_parts = _build_forge_command(
        forge_bin=forge_bin,
        kernel_file=kernel_file,
        driver_dest=driver_dest,
        workspace=workspace,
        experiments_dir=experiments_dir,
        result_json=result_json,
        agent_config=agent_config,
        gpu_arch=gpu_arch,
        gpu_type=gpu_type,
        fellow=fellow,
        task_type=task_type,
        source_files=all_source_files,
        target_functions=target_funcs,
        logical_operator=logical_operator,
        framework=framework,
    )
    # Human-readable rendering for the log only; the process is launched from the
    # argv list (cmd_parts) with shell=False, so no shell parsing is involved.
    cmd = " ".join(shlex.quote(p) for p in cmd_parts)

    logger.info("Forge Preflight")
    logger.info(f"  forge bin:   {forge_bin}")
    logger.info(f"  kernel:      {kernel_file}")
    logger.info(f"  driver:      {driver_dest}")
    logger.info(f"  gpu target:  {gpu_arch}")
    logger.info(f"  gpu type:    {gpu_type}")
    logger.info(f"  model:       {model}")
    logger.info(f"  fellow:      {fellow} (resolved from task configuration)")
    logger.info(f"  operator:    {logical_operator or '<forge inference>'}")
    logger.info(f"  kernel kind: {kernel_kind}")
    logger.info(f"  source owner:{framework or '<unknown>'}")
    logger.info(f"  budget:      {agent_config.get('max_iters')} iters / {_forge_max_hours(agent_config)}h")
    logger.info(f"  gateway:     {env.get('ANTHROPIC_BASE_URL', '<unset>')}")
    logger.info(f"Running command: {cmd}")
    logger.info("=" * 80)
    logger.info("Forge Output (streaming):")
    logger.info("=" * 80)

    timeout_seconds = int(agent_config.get("timeout_seconds", 3600))
    process, stdout_lines, stderr_lines, timed_out = run_forge_subprocess(
        cmd_parts,
        workspace=workspace,
        env=env,
        timeout_seconds=timeout_seconds,
        logger=logger,
    )

    logger.info("=" * 80)
    logger.info(f"Forge loop completed with exit code: {process.returncode}")
    logger.info("=" * 80)

    # Restore the workspace working tree to the loop's final (best-kept) state.
    # The loop runs on the 'forge-optimize' branch; ensure no partial/uncommitted
    # revert leaves the tree dirty before Arena re-scores.
    _git(workspace, "checkout", "--", ".", logger=logger)
    undeclared_edits = _verify_forge_edit_scope(
        workspace,
        edit_baseline,
        all_source_files,
        logger,
    )

    output = "\n".join(stdout_lines)
    if undeclared_edits:
        # Carried into the scored output so a reader of the report can tell that
        # this speedup rests partly on files the task did not declare editable.
        output += "\n=== UNDECLARED EDITS ===\n" + "\n".join(undeclared_edits)
    if stderr_lines:
        output += "\n=== STDERR ===\n" + "\n".join(stderr_lines)
    forge_result = _read_forge_result(result_json, "\n".join(stdout_lines))
    kb_status = _publication_status(forge_result)
    _write_forge_status(
        experiments_dir,
        returncode=process.returncode,
        timed_out=timed_out,
        result=forge_result,
        kb_status=kb_status,
    )
    logger.info(
        "Forge result: exit=%s timed_out=%s KB=%s (%s)",
        process.returncode,
        timed_out,
        kb_status["state"],
        kb_status["reason"] or "no error",
    )
    return output
