#!/usr/bin/env python3
"""Self-contained, forge-loop-format driver for mxfp8_linear (MERGED single file).

ONE file that combines what the Arena suite normally splits across
``scripts/task_runner.py`` (operator contract: cases, _make/_run/_reference,
graph-timed benchmark) and ``scripts/forge_driver.py`` (the forge-loop CLI
contract: ``--profile-run`` / ``--bench-mode`` / ``allclose:`` / ``case_ms:`` /
``mean_ms:``), with ``session_cases.json`` inlined as ``_SESSION_CASES_JSON`` --
so it needs NO sibling files.

It is a drop-in for ``scripts/forge_driver.py``: forge-loop copies the task's
``scripts/forge_driver.py`` verbatim to the workspace root and runs
``python forge_driver.py <args>`` reading only stdout. To have forge-loop use
THIS merged file, place it at ``scripts/forge_driver.py`` (it is a strict
superset of the thin delegator). ``WORKSPACE`` is resolved robustly so it works
whether it runs from the task ``scripts/`` dir (Arena) or the workspace root
(the forge copy).

AUTO-GENERATED by merging task_runner.py + forge_driver.py; do not hand-edit --
regenerate from those two files instead.
"""
from __future__ import annotations

import argparse
import importlib
import importlib.util
import json
import os
import sys
from pathlib import Path



import argparse
import json
import os
import sys
from pathlib import Path

_SESSION_CASES_JSON = r"""{
  "source_day": "2026-07-23",
  "date_field": "geak_capture + model_config",
  "platform": "MI355X/gfx950",
  "framework": "sglang origin/main MXFP8 (v0.5.12-rocm720-mi35x)",
  "base_image": "harbor.crusoe.primus-safe.amd.com/proxy/primussafe/sglang:v0.5.12-rocm720-mi35x-profilerfix",
  "model": "MiniMax-M3-MXFP8",
  "session_id": "17520246-e676-42be-83b4-6741291d723f",
  "operator": "mxfp8_linear",
  "kernel": "_mxfp8_linear_kernel",
  "timed_callable": "_run_mxfp8_linear_kernel",
  "task_name": "mi355x-sg-mxfp8-linear",
  "gpu_pct": 17.04,
  "profile": {
    "calls": 5520,
    "total_ms": 424.7126,
    "pct_gpu_time": 17.04
  },
  "quant": {
    "scheme": "mxfp8_ocp_1x32_e8m0",
    "operand_dtype": "float8_e4m3fn",
    "scale_dtype": "uint8_e8m0",
    "block_size": [1, 32],
    "out_dtype": "bfloat16",
    "accumulate": "fp32"
  },
  "provenance": "shapes from geak/e2e_cycle0/kernels/_mxfp8_linear_kernel_task/meta.json (families qkv_proj/o_proj, decode/prefill M buckets) captured from the live TP=8 MiniMax-M3 server; K/N confirmed against model config.json (hidden=6144, num_attention_heads=64, num_key_value_heads=4, head_dim=128, TP=8).",
  "cases": [
    {
      "id": "qkv_proj-decode-m1",
      "family": "qkv_proj",
      "regime": "decode",
      "params": {"m": 1, "n": 1280, "k": 6144, "max_relerr": 0.06}
    },
    {
      "id": "qkv_proj-decode-m64",
      "family": "qkv_proj",
      "regime": "decode",
      "params": {"m": 64, "n": 1280, "k": 6144, "max_relerr": 0.06}
    },
    {
      "id": "qkv_proj-prefill-m16384",
      "family": "qkv_proj",
      "regime": "prefill",
      "params": {"m": 16384, "n": 1280, "k": 6144, "max_relerr": 0.06}
    },
    {
      "id": "o_proj-decode-m1",
      "family": "o_proj",
      "regime": "decode",
      "params": {"m": 1, "n": 6144, "k": 1024, "max_relerr": 0.06}
    },
    {
      "id": "o_proj-decode-m64",
      "family": "o_proj",
      "regime": "decode",
      "params": {"m": 64, "n": 6144, "k": 1024, "max_relerr": 0.06}
    },
    {
      "id": "o_proj-prefill-m16384",
      "family": "o_proj",
      "regime": "prefill",
      "params": {"m": 16384, "n": 6144, "k": 1024, "max_relerr": 0.06}
    }
  ]
}
"""


def _resolve_workspace() -> Path:
    """Workspace root whether this file runs from the task ``scripts/`` dir
    (Arena) or from the workspace root (the copy forge-loop makes). Anchored on
    the always-present ``config.yaml``."""
    here = Path(__file__).resolve().parent
    for cand in (here.parent, here):
        if (cand / "config.yaml").is_file():
            return cand
    return here.parent


WORKSPACE = _resolve_workspace()
SPEC = json.loads(_SESSION_CASES_JSON)
CASES = SPEC["cases"]


def _configure() -> None:
    for key in ("GPU_ARCHS", "PYTORCH_ROCM_ARCH", "AMDGPU_TARGETS", "GPU_TARGETS"):
        os.environ.setdefault(key, "gfx950")
    # Prefer the workspace-seeded editable copy so the agent's edits take effect;
    # fall back to the in-image install for standalone/dev runs.
    seeded = WORKSPACE / "sglang"
    if (seeded / "__init__.py").is_file():
        sys.path.insert(0, str(WORKSPACE))
    else:
        sys.path.insert(0, os.environ.get("SGLANG_PYTHON", "/sgl-workspace/sglang/python"))
    os.chdir(WORKSPACE)


def _torch():
    import torch

    if not torch.cuda.is_available():
        raise RuntimeError("ROCm GPU (gfx950) is required")
    return torch


def _relerr(a, b) -> float:
    a = a.float()
    b = b.float()
    return float(((a - b).norm() / (b.norm() + 1e-8)).item())


# --------------------------------------------------------------------------- #
# CUDA-graph benchmark: capture N kernel launches, replay, time the graph. This
# amortizes host launch overhead so the measurement reflects device time only.
# Falls back to per-call CUDA-event timing if graph capture is unavailable.
# --------------------------------------------------------------------------- #
def _measure_cuda_event(fn, repetition):
    import torch

    times_ms = []
    for _ in range(max(1, int(repetition))):
        torch.cuda.synchronize()
        start = torch.cuda.Event(enable_timing=True)
        end = torch.cuda.Event(enable_timing=True)
        start.record()
        fn()
        end.record()
        torch.cuda.synchronize()
        times_ms.append(start.elapsed_time(end))
    return times_ms


def _benchmark_cuda_graph(fn, warmup=10, repetition=100, target_ms=1.0, max_graph_repeats=200):
    import torch

    for _ in range(max(0, int(warmup))):
        fn()
    torch.cuda.synchronize()

    meta = {"benchmark_target_ms": float(target_ms), "benchmark_samples": int(repetition)}
    try:
        stream = torch.cuda.Stream()
        stream.wait_stream(torch.cuda.current_stream())
        with torch.cuda.stream(stream):
            est = torch.cuda.CUDAGraph()
            with torch.cuda.graph(est):
                for _ in range(3):
                    fn()
            torch.cuda.synchronize()
            s, e = torch.cuda.Event(enable_timing=True), torch.cuda.Event(enable_timing=True)
            s.record(stream)
            est.replay()
            e.record(stream)
            torch.cuda.synchronize()
            est_ms = s.elapsed_time(e) / 3
            repeats = min(max_graph_repeats, max(1, int(target_ms / max(est_ms, 1e-9))))

            graph = torch.cuda.CUDAGraph()
            with torch.cuda.graph(graph):
                for _ in range(repeats):
                    fn()
            torch.cuda.synchronize()

            times = []
            for _ in range(max(1, int(repetition))):
                s, e = torch.cuda.Event(enable_timing=True), torch.cuda.Event(enable_timing=True)
                s.record(stream)
                graph.replay()
                e.record(stream)
                torch.cuda.synchronize()
                times.append(s.elapsed_time(e) / repeats)
        mean_ms = sum(times) / len(times)
        if mean_ms < 1e-5:
            raise RuntimeError("empty_cuda_graph_capture")
        meta.update(benchmark_method="cuda_graph", benchmark_effective_repeats=int(repeats))
        return mean_ms, meta
    except Exception as exc:
        try:
            torch.cuda.synchronize()
        except Exception:
            pass
        times = _measure_cuda_event(fn, repetition)
        meta.update(
            benchmark_method="cuda_event_fallback",
            benchmark_effective_repeats=int(repetition),
            benchmark_fallback_reason=f"{type(exc).__name__}: {str(exc)[:160]}",
        )
        return sum(times) / len(times), meta


# --------------------------------------------------------------------------- #
# Inputs / call / reference
# --------------------------------------------------------------------------- #
def _make(case: dict) -> dict:
    torch = _torch()
    from sglang.kernels.ops.quantization.mxfp8_amd_gfx95 import (
        _mxfp8_e4m3_quantize_torch,
        mxfp8_e4m3_quantize,
    )

    p = case["params"]
    m, n, k = p["m"], p["n"], p["k"]
    torch.manual_seed(case.get("seed", 0))

    # Weight: FP8-E4M3 + UE8M0 per-1x32 block scale (the persisted model weight).
    w_bf16 = torch.randn(n, k, device="cuda", dtype=torch.bfloat16) * 0.1
    w_fp8, w_scale = _mxfp8_e4m3_quantize_torch(w_bf16)
    # Activation: MXFP8-quantized once (as the server does before the GEMM).
    x_bf16 = torch.randn(m, k, device="cuda", dtype=torch.bfloat16) * 0.5
    x_fp8, x_scale = mxfp8_e4m3_quantize(x_bf16)
    return {
        "cfg": case,
        "x_fp8": x_fp8,
        "x_scale": x_scale,
        "w_fp8": w_fp8,
        "w_scale": w_scale,
    }


def _run(inputs: dict):
    torch = _torch()
    from sglang.kernels.ops.quantization.mxfp8_amd_gfx95 import _run_mxfp8_linear_kernel

    return _run_mxfp8_linear_kernel(
        inputs["x_fp8"],
        inputs["x_scale"],
        inputs["w_fp8"],
        inputs["w_scale"],
        torch.bfloat16,
    )


def _reference(inputs: dict):
    torch = _torch()
    from sglang.kernels.ops.quantization.mxfp8_amd_gfx95 import dequant_mxfp8_to_bf16

    x = dequant_mxfp8_to_bf16(inputs["x_fp8"], inputs["x_scale"])
    w = dequant_mxfp8_to_bf16(inputs["w_fp8"], inputs["w_scale"])
    return torch.nn.functional.linear(x, w).to(torch.bfloat16)


# --------------------------------------------------------------------------- #
# Modes
# --------------------------------------------------------------------------- #
def run_compile() -> None:
    inputs = _make(CASES[0])
    _run(inputs)
    _torch().cuda.synchronize()
    print("mxfp8_linear compile smoke: PASS")


def run_correctness() -> None:
    torch = _torch()
    for case in CASES:
        inputs = _make(case)
        got = _run(inputs)
        torch.cuda.synchronize()
        err = _relerr(got, _reference(inputs))
        tol = case["params"].get("max_relerr", 0.06)
        assert err < tol, (case["id"], err, tol)
        print("correctness PASS", case["id"], f"relerr={err:.4f}")


def run_performance() -> None:
    torch = _torch()
    rows = []
    for case in CASES:
        inputs = _make(case)
        _run(inputs)
        torch.cuda.synchronize()
        ms, bmeta = _benchmark_cuda_graph(lambda: _run(inputs))
        row = {
            "test_case_id": case["id"],
            "execution_time_ms": ms,
            "metadata": {**case["params"], "family": case.get("family"),
                         "regime": case.get("regime"), **bmeta},
        }
        rows.append(row)
        print(case["id"], f"{ms:.6f} ms", bmeta.get("benchmark_method"),
              bmeta.get("benchmark_fallback_reason", ""))
    out = WORKSPACE / "build"
    out.mkdir(parents=True, exist_ok=True)
    (out / "performance_report.json").write_text(json.dumps(rows, indent=2))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("mode", choices=["compile", "correctness", "performance", "manifest"])
    mode = parser.parse_args().mode
    if mode == "manifest":
        print(json.dumps(SPEC, indent=2))
        return
    _configure()
    {"compile": run_compile, "correctness": run_correctness, "performance": run_performance}[mode]()


import argparse
import importlib.util
import sys
from pathlib import Path



def _import_task_runner():
    """This merged file inlines task_runner above; return this module."""
    return sys.modules[__name__]

def _case_map(tr):
    return {c["id"]: c for c in tr.CASES}


def _case_size(case: dict) -> int:
    p = case["params"]
    return int(p["m"]) * int(p["n"]) * int(p["k"])


def _run_correctness(tr, mode: str) -> int:
    """Reuse the harness's kernel-vs-reference check; gate on relerr, not SNR."""
    torch = tr._torch()
    all_ok = True
    for case in tr.CASES:
        inputs = tr._make(case)
        got = tr._run(inputs)
        torch.cuda.synchronize()
        err = tr._relerr(got, tr._reference(inputs))
        tol = case["params"].get("max_relerr", 0.06)
        ok = err < tol
        all_ok = all_ok and ok
        # Informational only. Intentionally NOT the "SNR:" token (see module doc).
        print(f"# case {case['id']}: relerr={err:.4f} tol={tol} ok={ok}")
    print(f"allclose: {all_ok}")
    return 0


def _run_bench(tr, warmup: int, iters: int) -> int:
    """Graph-timed bench: one CUDA-graph mean per case (reuses task_runner)."""
    torch = tr._torch()
    means = []
    for case in tr.CASES:
        inputs = tr._make(case)
        tr._run(inputs)  # warm/JIT settle before capture
        torch.cuda.synchronize()
        ms, meta = tr._benchmark_cuda_graph(
            lambda i=inputs: tr._run(i),
            warmup=max(1, warmup),
            repetition=max(1, iters),
        )
        means.append(ms)
        # Per-case time (forge can round-trip the case_id to --profile-case).
        print(f"case_ms: {case['id']} {ms:.6f}")
        print(f"# bench {case['id']}: {ms:.6f} ms method={meta.get('benchmark_method')}"
              f" {meta.get('benchmark_fallback_reason', '')}".rstrip())
    # Aggregate forge uses for keep/revert = arithmetic mean across cases
    # (matches arena_task_adapter / Arena's evaluator). Label it honestly.
    agg = sum(means) / len(means)
    print(f"mean_ms: {agg:.6f}")
    return 0


def _run_profile(tr, case_id: str) -> int:
    """Kernel-only profiling for one case: warm, a few launches, sync, exit 0."""
    torch = tr._torch()
    cases = _case_map(tr)
    if case_id and case_id in cases:
        case = cases[case_id]
    else:
        # Default: the largest / dominant case (biggest M*N*K) when unspecified.
        case = max(tr.CASES, key=_case_size)
    inputs = tr._make(case)
    for _ in range(5):          # settle Triton JIT / autotune selection
        tr._run(inputs)
    torch.cuda.synchronize()
    for _ in range(3):          # profiled launches (profiler replays per group)
        tr._run(inputs)
    torch.cuda.synchronize()
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="SGLang MXFP8 dense-GEMM forge driver")
    parser.add_argument("--shape", default="default")  # task owns its shapes
    parser.add_argument("--mode", default="full")       # all modes -> task correctness
    parser.add_argument("--bench-mode", action="store_true")
    parser.add_argument("--profile-run", action="store_true")
    parser.add_argument("--profile-case", default="")
    parser.add_argument("--warmup", type=int, default=10)
    parser.add_argument("--iters", type=int, default=30)
    args, _unknown = parser.parse_known_args()

    tr = _import_task_runner()
    tr._configure()  # set gfx950 arch env + make the seeded sglang copy importable

    import torch
    if not torch.cuda.is_available():
        print("error: ROCm GPU (gfx950) is required (torch.cuda.is_available() is False)",
              file=sys.stderr)
        return 1

    if args.profile_run:
        return _run_profile(tr, args.profile_case)
    if args.bench_mode:
        return _run_bench(tr, args.warmup, args.iters)
    return _run_correctness(tr, args.mode)


if __name__ == "__main__":
    sys.exit(main())
