source_file_path:
- pytorch_code_module/py_l2n17_Conv2d_InstanceNorm_Divide.py
target_kernel_functions:
- forward
compile_command:
- python3 eval_tools/compile.py --hip_file hip/hip_l2n17_Conv2d_InstanceNorm_Divide.hip
correctness_command:
- python3 eval_tools/correctness_check.py --py_modu_file pytorch_code_module/py_l2n17_Conv2d_InstanceNorm_Divide.py
  --py_func_file pytorch_code_functional/py_l2n17_Conv2d_InstanceNorm_Divide_func.py --hip_file hip/hip_l2n17_Conv2d_InstanceNorm_Divide.hip
performance_command:
- python3 eval_tools/cal_kernel_perf.py --py_modu_file pytorch_code_module/py_l2n17_Conv2d_InstanceNorm_Divide.py
  --py_func_file pytorch_code_functional/py_l2n17_Conv2d_InstanceNorm_Divide_func.py --hip_file hip/hip_l2n17_Conv2d_InstanceNorm_Divide.hip
prompt:
  source_code: null
  instructions: You are a HIP expert skilled at GPU kernel implementation. Please
    implement target HIP kernel code corresponding to the provided PyTorch module,
    including the HIP kernel, kernel launcher, and Python binding code
    for the HIP launcher.
  task_type: null
  cheatsheet: null
target_file_path: hip/hip_l2n17_Conv2d_InstanceNorm_Divide.hip
task_type: torch2hip
task_result_template: null
