#!/usr/bin/env python3
"""Self-contained, forge-loop-format driver for fused_moe_gptq_awq (MERGED single file).

ONE file that combines what the Arena suite normally splits across
``scripts/task_runner.py`` (operator contract: cases, _make/_run/_reference,
graph-timed benchmark) and ``scripts/forge_driver.py`` (the forge-loop CLI
contract: ``--profile-run`` / ``--bench-mode`` / ``allclose:`` / ``case_ms:`` /
``mean_ms:``), with ``session_cases.json`` inlined as ``_SESSION_CASES_JSON`` --
so it needs NO sibling files.

It is a drop-in for ``scripts/forge_driver.py``: forge-loop copies the task's
``scripts/forge_driver.py`` verbatim to the workspace root and runs
``python forge_driver.py <args>`` reading only stdout. To have forge-loop use
THIS merged file, place it at ``scripts/forge_driver.py`` (it is a strict
superset of the thin delegator). ``WORKSPACE`` is resolved robustly so it works
whether it runs from the task ``scripts/`` dir (Arena) or the workspace root
(the forge copy).

AUTO-GENERATED by merging task_runner.py + forge_driver.py; do not hand-edit --
regenerate from those two files instead.
"""
from __future__ import annotations

import argparse
import importlib
import importlib.util
import json
import os
import sys
from pathlib import Path



import argparse
import importlib.util
import json
import os
import sys
from pathlib import Path

_SESSION_CASES_JSON = r"""{
  "source_day": "2026-07-24",
  "date_field": "session_ended_at",
  "platform": "MI355X/gfx950",
  "framework": "vllm 0.24.0",
  "base_image": "harbor.crusoe.primus-safe.amd.com/sync/vllm-openai-rocm:v0.24.0",
  "selection": "hot MoE leaf fused_moe_kernel_gptq_awq; WNA16 int4 GPTQ/AWQ experts; real Kimi-K2.7-Code config",
  "task_name": "mi355x-kimi-k2.7-code-fused-moe-gptq-awq-20260724",
  "operator": "fused_moe_gptq_awq",
  "provenance": {
    "model": "Kimi-K2.7-Code",
    "session_id": "0e13b6b5-a63f-44e2-b6ff-cc2308e6cb82",
    "device_kernel": "fused_moe_kernel_gptq_awq",
    "entry": "vllm/model_executor/layers/fused_moe/fused_moe.py: fused_moe_kernel_gptq_awq (launched by invoke_fused_moe_wna16_triton_kernel; orchestrated by fused_experts_impl)",
    "call_chain": "compressed_tensors_moe_wna16.apply -> fused_experts -> fused_experts_impl -> invoke_fused_moe_wna16_triton_kernel -> fused_moe_kernel_gptq_awq",
    "why_triton": "should_moe_wna16_use_cuda() requires current_platform.is_cuda(), which is False on ROCm; the int4 weight-only MoE therefore always uses this Triton kernel on gfx950.",
    "config": {
      "num_experts": 384,
      "topk": 8,
      "hidden": 7168,
      "intermediate_per_rank": 256,
      "tensor_parallel": 8,
      "weight_bits": 4,
      "group_size": 32,
      "has_zero_point": false,
      "act_dtype": "bf16",
      "scale_dtype": "bf16",
      "source": "Kimi-K2.7-Code (hidden_size=7168, num_experts_per_tok=8, 384 routed experts, moe_intermediate_size=2048 -> per-rank 256 under TP=8). int4/group_size=32 inferred from observed weight/scale shapes w1 (384,512,3584), w2 (384,7168,128), scale (384,7168,8): 256/8=32."
    },
    "notes": "Weight/activation/routing shapes are from the trace (activation (M,7168) bf16; weight storage (384,512,3584)/(384,7168,128); scale (384,7168,8); routing (M,8)). Weights are synthesized as random int4 (symmetric, zero-point=8) with per-group bf16 scales; both kernel and reference use the identical dequantized weights so correctness is exact up to bf16 rounding. Token buckets M are the model's observed prefill/decode counts. The two same-named leaf sequences reported (43.862% and 30.391% E2E) are aggregate over these buckets."
  },
  "cases": [
    {
      "id": "kimi-k2.7-moe-m7211",
      "model": "Kimi-K2.7-Code",
      "session_id": "0e13b6b5-a63f-44e2-b6ff-cc2308e6cb82",
      "kernel_ids": ["gptq-awq-seq"],
      "gpu_pct": 43.862,
      "params": {
        "tokens": 7211,
        "num_experts": 384,
        "topk": 8,
        "hidden": 7168,
        "inter": 256,
        "group_size": 32,
        "weight_bits": 4,
        "has_zero_point": false,
        "dtype": "bf16"
      },
      "trace_input_shapes": [
        "activation (7211,7168) bf16",
        "w1 (384,512,3584) int4-packed uint8",
        "w2 (384,7168,128) int4-packed uint8",
        "scale (384,7168,8) bf16",
        "routing (7211,8)"
      ]
    },
    {
      "id": "kimi-k2.7-moe-m1080",
      "model": "Kimi-K2.7-Code",
      "session_id": "0e13b6b5-a63f-44e2-b6ff-cc2308e6cb82",
      "kernel_ids": ["gptq-awq-seq"],
      "gpu_pct": null,
      "params": {
        "tokens": 1080,
        "num_experts": 384,
        "topk": 8,
        "hidden": 7168,
        "inter": 256,
        "group_size": 32,
        "weight_bits": 4,
        "has_zero_point": false,
        "dtype": "bf16"
      },
      "trace_input_shapes": [
        "activation (1080,7168) bf16",
        "w1 (384,512,3584) int4-packed uint8",
        "w2 (384,7168,128) int4-packed uint8",
        "scale (384,7168,8) bf16",
        "routing (1080,8)"
      ]
    },
    {
      "id": "kimi-k2.7-moe-m64",
      "model": "Kimi-K2.7-Code",
      "session_id": "0e13b6b5-a63f-44e2-b6ff-cc2308e6cb82",
      "kernel_ids": ["gptq-awq-seq"],
      "gpu_pct": null,
      "params": {
        "tokens": 64,
        "num_experts": 384,
        "topk": 8,
        "hidden": 7168,
        "inter": 256,
        "group_size": 32,
        "weight_bits": 4,
        "has_zero_point": false,
        "dtype": "bf16"
      },
      "trace_input_shapes": [
        "activation (64,7168) bf16",
        "w1 (384,512,3584) int4-packed uint8",
        "w2 (384,7168,128) int4-packed uint8",
        "scale (384,7168,8) bf16",
        "routing (64,8)"
      ]
    }
  ]
}
"""


def _resolve_workspace() -> Path:
    """Workspace root whether this file runs from the task ``scripts/`` dir
    (Arena) or from the workspace root (the copy forge-loop makes). Anchored on
    the always-present ``config.yaml``."""
    here = Path(__file__).resolve().parent
    for cand in (here.parent, here):
        if (cand / "config.yaml").is_file():
            return cand
    return here.parent


WORKSPACE = _resolve_workspace()
SPEC = json.loads(_SESSION_CASES_JSON)
OPERATOR = SPEC["operator"]
CASES = SPEC["cases"]

REPO_SUBDIR = "vllm_fused_moe"
KERNEL_FILE = "fused_moe.py"
EDIT_MODULE_NAME = "vllm.model_executor.layers.fused_moe._ka_fused_moe"


def _configure() -> None:
    for key in ("GPU_ARCHS", "PYTORCH_ROCM_ARCH", "AMDGPU_TARGETS", "GPU_TARGETS"):
        os.environ.setdefault(key, "gfx950")
    os.chdir(WORKSPACE)


# >>> AKA-GENERATED: shared CUDA-graph benchmark helpers - edit src/tools/perf/vllm_cuda_graph_block.py then run `make sync-perf-helpers` >>>
def _measure_cuda_event_fallback(fn, repetition):
    import time
    import torch

    repetition = max(1, int(repetition))
    if not torch.cuda.is_available():
        times_ms = []
        for _ in range(repetition):
            start = time.perf_counter()
            fn()
            end = time.perf_counter()
            times_ms.append((end - start) * 1000.0)
        return times_ms

    times_ms = []
    for _ in range(repetition):
        torch.cuda.synchronize()
        start_event = torch.cuda.Event(enable_timing=True)
        end_event = torch.cuda.Event(enable_timing=True)
        start_event.record()
        fn()
        end_event.record()
        torch.cuda.synchronize()
        times_ms.append(start_event.elapsed_time(end_event))
    return times_ms


def _benchmark_cuda_graph_or_events(
    fn,
    warmup=10,
    repetition=100,
    target_ms=1.0,
    n_retries=5,
    estimate_reps=5,
    max_graph_repeats=1000,
    use_cuda_graph=True,
    fallback_reason=None,
):
    import torch

    # A captured graph whose measured per-iteration time falls below this floor is
    # treated as empty (it recorded no device work) and rejected in favour of
    # per-launch event timing, so a graph that silently captured nothing is never
    # reported as a fabricated ~0 ms cuda_graph result. Real kernels measure far
    # above this floor; an empty-graph replay measures ~1e-5 ms.
    empty_graph_floor_ms = 1e-4

    for _ in range(max(0, int(warmup))):
        fn()
    if torch.cuda.is_available():
        torch.cuda.synchronize()

    max_graph_repeats = max(1, int(max_graph_repeats))
    metadata = {
        "benchmark_target_ms": float(target_ms),
        "benchmark_samples": int(repetition),
        "benchmark_max_repeats": int(max_graph_repeats),
    }

    if not torch.cuda.is_available():
        times = _measure_cuda_event_fallback(fn, repetition)
        metadata.update({
            "benchmark_method": "cpu_timer_fallback",
            "benchmark_effective_repeats": int(repetition),
            "benchmark_fallback_reason": fallback_reason or "cuda_unavailable",
        })
        return sum(times) / len(times), metadata

    if not use_cuda_graph:
        times = _measure_cuda_event_fallback(fn, repetition)
        metadata.update({
            "benchmark_method": "cuda_event_fallback",
            "benchmark_effective_repeats": int(repetition),
            "benchmark_fallback_reason": fallback_reason or "cuda_graph_disabled",
        })
        return sum(times) / len(times), metadata

    try:
        stream = torch.cuda.Stream()
        stream.wait_stream(torch.cuda.current_stream())
        with torch.cuda.stream(stream):
            estimate_reps = max(1, int(estimate_reps))
            estimate_graph = torch.cuda.CUDAGraph()
            with torch.cuda.graph(estimate_graph):
                for _ in range(estimate_reps):
                    fn()
            torch.cuda.synchronize()

            start_event = torch.cuda.Event(enable_timing=True)
            end_event = torch.cuda.Event(enable_timing=True)
            start_event.record(stream)
            estimate_graph.replay()
            end_event.record(stream)
            torch.cuda.synchronize()

            estimate_ms = start_event.elapsed_time(end_event) / estimate_reps
            if estimate_ms == 0:
                n_repeat = max_graph_repeats
            else:
                n_repeat = min(max_graph_repeats, max(1, int(float(target_ms) / estimate_ms)))

            graph = torch.cuda.CUDAGraph()
            with torch.cuda.graph(graph):
                for _ in range(n_repeat):
                    fn()
            torch.cuda.synchronize()

            retry_times = []
            for _ in range(max(1, int(repetition))):
                start_event = torch.cuda.Event(enable_timing=True)
                end_event = torch.cuda.Event(enable_timing=True)
                start_event.record(stream)
                graph.replay()
                end_event.record(stream)
                torch.cuda.synchronize()
                retry_times.append(start_event.elapsed_time(end_event) / n_repeat)

        graph_mean = sum(retry_times) / len(retry_times)
        if graph_mean < empty_graph_floor_ms:
            times = _measure_cuda_event_fallback(fn, repetition)
            metadata.update({
                "benchmark_method": "cuda_event_fallback",
                "benchmark_effective_repeats": int(repetition),
                "benchmark_fallback_reason": fallback_reason or "empty_cuda_graph_capture",
            })
            return sum(times) / len(times), metadata

        metadata.update({
            "benchmark_method": "cuda_graph",
            "benchmark_effective_repeats": int(n_repeat),
        })
        return graph_mean, metadata
    except Exception as exc:
        # Isolate the aborted capture before re-measuring so the fallback timing is
        # not polluted by the failed attempt (a mid-capture failure can leave the
        # first few launches abnormally slow).
        try:
            torch.cuda.synchronize()
        except Exception:
            pass
        for _ in range(min(3, max(1, int(warmup)))):
            fn()
        torch.cuda.synchronize()
        times = _measure_cuda_event_fallback(fn, repetition)
        metadata.update({
            "benchmark_method": "cuda_event_fallback",
            "benchmark_effective_repeats": int(repetition),
            "benchmark_fallback_reason": f"cuda_graph_failed: {type(exc).__name__}: {str(exc)[:160]}",
        })
        return sum(times) / len(times), metadata
# <<< AKA-GENERATED <<<


def _write_report(rows: list[dict]) -> None:
    report_dir = WORKSPACE / "build"
    report_dir.mkdir(parents=True, exist_ok=True)
    (report_dir / "performance_report.json").write_text(json.dumps(rows, indent=2))


def _torch():
    import torch

    if not torch.cuda.is_available():
        raise RuntimeError("ROCm GPU is required")
    return torch


def _load_kernel_module():
    # fused_moe.py runs direct_register_custom_op at import; suppress it so loading
    # the editable copy does not clash with the already-registered installed copy.
    import vllm.model_executor.layers.fused_moe.fused_moe  # noqa: F401
    import vllm.utils.torch_utils as torch_utils

    path = WORKSPACE / REPO_SUBDIR / KERNEL_FILE
    spec = importlib.util.spec_from_file_location(EDIT_MODULE_NAME, path)
    module = importlib.util.module_from_spec(spec)
    assert spec and spec.loader
    sys.modules[EDIT_MODULE_NAME] = module
    original = torch_utils.direct_register_custom_op
    torch_utils.direct_register_custom_op = lambda *a, **k: None
    try:
        spec.loader.exec_module(module)
    finally:
        torch_utils.direct_register_custom_op = original
    return module


def _quant_pack_int4(w: "object", group_size: int):
    """Symmetric int4 (zero-point=8) group quant along the last (K) dim.

    Returns (packed_uint8 [E,N,K//2], scale_bf16 [E,N,K//group], deq_bf16 [E,N,K]).
    Matches the kernel dequant: deq = (q - 8) * scale, packed low nibble = even k.
    """
    torch = _torch()
    E, N, K = w.shape
    ng = K // group_size
    wg = w.reshape(E, N, ng, group_size).float()
    scale = (wg.abs().amax(dim=-1) / 7.0).clamp(min=1e-4)  # [E,N,ng]
    q = torch.round(wg / scale.unsqueeze(-1)) + 8.0
    q = q.clamp(0, 15)  # [E,N,ng,group_size]
    deq = ((q - 8.0) * scale.unsqueeze(-1)).reshape(E, N, K).to(torch.bfloat16)
    q = q.to(torch.uint8).reshape(E, N, K // 2, 2)
    packed = (q[..., 0] | (q[..., 1] << 4)).contiguous()  # [E,N,K//2]
    return packed, scale.to(torch.bfloat16).contiguous(), deq


def _make(case: dict, correctness: bool = False) -> dict:
    torch = _torch()
    p = dict(case["params"])
    if correctness:
        tokens = min(p["tokens"], 16)
        num_experts = min(p["num_experts"], 8)
        topk = min(p["topk"], 2)
        hidden = min(p["hidden"], 512)
        inter = min(p["inter"], 128)
    else:
        tokens = p["tokens"]
        num_experts = p["num_experts"]
        topk = p["topk"]
        hidden = p["hidden"]
        inter = p["inter"]
    group_size = p["group_size"]
    assert hidden % group_size == 0 and inter % group_size == 0

    torch.manual_seed(31)
    module = _load_kernel_module()

    # Scale inputs/weights so the MoE output is O(1); this keeps the correctness
    # tolerance meaningful (tiny outputs would let a broken kernel pass under a
    # fixed atol). Reductions to K are normalized by 1/sqrt(K).
    x = torch.randn((tokens, hidden), device="cuda", dtype=torch.bfloat16)

    # w1 gate/up: [E, 2*inter, hidden] ; w2 down: [E, hidden, inter]
    w1 = (
        torch.randn((num_experts, 2 * inter, hidden), device="cuda", dtype=torch.bfloat16)
        / (hidden**0.5)
    )
    w2 = (
        torch.randn((num_experts, hidden, inter), device="cuda", dtype=torch.bfloat16)
        / (inter**0.5)
    )
    w1_packed, w1_scale, w1_deq = _quant_pack_int4(w1, group_size)
    w2_packed, w2_scale, w2_deq = _quant_pack_int4(w2, group_size)
    del w1, w2

    # routing: top-k experts per token
    logits = torch.randn((tokens, num_experts), device="cuda", dtype=torch.float32)
    topk_weights, topk_ids = torch.topk(torch.softmax(logits, dim=-1), topk, dim=-1)
    topk_weights = topk_weights.to(torch.float32).contiguous()
    topk_ids = topk_ids.to(torch.int32).contiguous()

    return {
        "cfg": case,
        "module": module,
        "x": x,
        "w1": w1_packed,
        "w2": w2_packed,
        "w1_scale": w1_scale,
        "w2_scale": w2_scale,
        "w1_deq": w1_deq if correctness else None,
        "w2_deq": w2_deq if correctness else None,
        "topk_weights": topk_weights,
        "topk_ids": topk_ids,
        "num_experts": num_experts,
        "group_size": group_size,
        "inter": inter,
    }


def _run(inputs: dict):
    return inputs["module"].fused_experts_impl(
        hidden_states=inputs["x"],
        w1=inputs["w1"],
        w2=inputs["w2"],
        topk_weights=inputs["topk_weights"],
        topk_ids=inputs["topk_ids"],
        activation="silu",
        use_int4_w4a16=True,
        global_num_experts=inputs["num_experts"],
        w1_scale=inputs["w1_scale"],
        w2_scale=inputs["w2_scale"],
        w1_zp=None,
        w2_zp=None,
        block_shape=[0, inputs["group_size"]],
    )


def _reference(inputs: dict):
    torch = _torch()
    import torch.nn.functional as F

    x = inputs["x"].float()  # [M, hidden]
    w1d = inputs["w1_deq"].float()  # [E, 2*inter, hidden]
    w2d = inputs["w2_deq"].float()  # [E, hidden, inter]
    tw = inputs["topk_weights"].float()  # [M, topk]
    tid = inputs["topk_ids"]  # [M, topk]
    inter = inputs["inter"]
    M, hidden = x.shape
    out = torch.zeros((M, hidden), device="cuda", dtype=torch.float32)
    for m in range(M):
        acc = torch.zeros((hidden,), device="cuda", dtype=torch.float32)
        for j in range(tid.shape[1]):
            e = int(tid[m, j].item())
            gu = x[m] @ w1d[e].t()  # [2*inter]
            gate = gu[:inter]
            up = gu[inter:]
            act = F.silu(gate) * up  # [inter]
            acc = acc + float(tw[m, j].item()) * (act @ w2d[e].t())
        out[m] = acc
    return out.to(torch.bfloat16)


def run_compile() -> None:
    inputs = _make(CASES[0], correctness=True)
    _run(inputs)
    _torch().cuda.synchronize()
    print(f"{OPERATOR} compile smoke: PASS")


def run_correctness() -> None:
    torch = _torch()
    for case in CASES:
        inputs = _make(case, correctness=True)
        got = _run(inputs)
        torch.cuda.synchronize()
        torch.testing.assert_close(
            got, _reference(inputs), atol=0.02, rtol=0.02
        )
        print("correctness PASS", case["id"])


def run_performance() -> None:
    rows = []
    for case in CASES:
        inputs = _make(case, correctness=False)
        _run(inputs)
        _torch().cuda.synchronize()
        execution_time_ms, bench_meta = _benchmark_cuda_graph_or_events(
            lambda: _run(inputs),
            warmup=10,
            repetition=100,
            target_ms=1.0,
            max_graph_repeats=1000,
        )
        metadata = {
            **case["params"],
            "model": case.get("model"),
            "session_id": case.get("session_id"),
            "kernel_ids": case.get("kernel_ids"),
            "gpu_pct": case.get("gpu_pct"),
            "benchmark_method": bench_meta.get("benchmark_method"),
        }
        metadata.update(
            {k: v for k, v in bench_meta.items() if k.startswith("benchmark_")}
        )
        rows.append(
            {
                "test_case_id": case["id"],
                "shape": case.get("trace_input_shapes"),
                "execution_time_ms": execution_time_ms,
                "metadata": metadata,
            }
        )
        print(
            case["id"],
            f"{execution_time_ms:.6f} ms",
            bench_meta.get("benchmark_method"),
            bench_meta.get("benchmark_fallback_reason", ""),
        )
    _write_report(rows)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "mode", choices=["compile", "correctness", "performance", "manifest"]
    )
    mode = parser.parse_args().mode
    if mode == "manifest":
        print(json.dumps(SPEC, indent=2))
        return
    _configure()
    if mode == "compile":
        run_compile()
    elif mode == "correctness":
        run_correctness()
    else:
        run_performance()


import argparse
import importlib.util
import json
import sys
from pathlib import Path



def _import_task_runner():
    """This merged file inlines task_runner above; return this module."""
    return sys.modules[__name__], Path(__file__).resolve().parent

def _report_path(tr) -> Path:
    return Path(tr.WORKSPACE) / "build" / "performance_report.json"


def _run_correctness(tr) -> int:
    """Delegate to the task's own per-operator correctness; map to allclose."""
    ok = True
    try:
        tr.run_correctness()  # asserts / raises on any failing case
    except Exception as exc:  # noqa: BLE001 - any failure is a correctness fail
        ok = False
        print(f"# correctness failed: {type(exc).__name__}: {str(exc)[:300]}")
    print(f"allclose: {ok}")
    return 0


def _run_bench(tr) -> int:
    """Delegate to the task's graph-timed run_performance(); expose per-case ms."""
    tr.run_performance()  # writes build/performance_report.json, graph-timed
    rows = json.loads(_report_path(tr).read_text())
    times = []
    for row in rows:
        cid = str(row.get("test_case_id", "")).replace(" ", "_")
        ms = row.get("execution_time_ms")
        if ms is None or float(ms) <= 0:
            continue
        times.append(float(ms))
        print(f"case_ms: {cid} {float(ms):.6f}")
    if not times:
        print("error: run_performance produced no usable timing", file=sys.stderr)
        return 1
    print(f"mean_ms: {sum(times) / len(times):.6f}")
    return 0


def _pick_profile_case(tr, case_id: str) -> dict:
    cases = {c["id"]: c for c in tr.CASES}
    if case_id and case_id in cases:
        return cases[case_id]
    # Fallback (forge normally passes --profile-case, derived from case_ms): use
    # the slowest case from a prior perf report if present, else the last case
    # (session cases are ordered decode->prefill, i.e. smallest->largest).
    rp = _report_path(tr)
    if rp.is_file():
        try:
            rows = json.loads(rp.read_text())
            best = max(rows, key=lambda r: float(r.get("execution_time_ms") or 0))
            if best.get("test_case_id") in cases:
                return cases[best["test_case_id"]]
        except Exception:  # noqa: BLE001 - best-effort fallback
            pass
    return tr.CASES[-1]


def _run_profile(tr, case_id: str) -> int:
    torch = tr._torch()
    case = _pick_profile_case(tr, case_id)
    inputs = tr._make(case, correctness=False)
    for _ in range(5):          # settle Triton JIT / autotune selection
        tr._run(inputs)
    torch.cuda.synchronize()
    for _ in range(3):          # profiled launches (profiler replays per group)
        tr._run(inputs)
    torch.cuda.synchronize()
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Generic image_kernel forge driver")
    parser.add_argument("--shape", default="default")  # task owns its shapes
    parser.add_argument("--mode", default="full")       # all modes -> task correctness
    parser.add_argument("--bench-mode", action="store_true")
    parser.add_argument("--profile-run", action="store_true")
    parser.add_argument("--profile-case", default="")
    parser.add_argument("--warmup", type=int, default=10)
    parser.add_argument("--iters", type=int, default=30)
    args, _unknown = parser.parse_known_args()

    tr, _scripts_dir = _import_task_runner()
    tr._configure()  # arch env + make the seeded (agent-editable) repo importable

    import torch
    if not torch.cuda.is_available():
        print("error: ROCm GPU (gfx950) is required (torch.cuda.is_available() is False)",
              file=sys.stderr)
        return 1

    if args.profile_run:
        return _run_profile(tr, args.profile_case)
    if args.bench_mode:
        return _run_bench(tr)
    return _run_correctness(tr)


if __name__ == "__main__":
    sys.exit(main())
