#!/usr/bin/env python3
"""Self-contained, forge-loop-format driver for unified_attention (MERGED single file).

ONE file that combines what the Arena suite normally splits across
``scripts/task_runner.py`` (operator contract: cases, _make/_run/_reference,
graph-timed benchmark) and ``scripts/forge_driver.py`` (the forge-loop CLI
contract: ``--profile-run`` / ``--bench-mode`` / ``allclose:`` / ``case_ms:`` /
``mean_ms:``), with ``session_cases.json`` inlined as ``_SESSION_CASES_JSON`` --
so it needs NO sibling files.

It is a drop-in for ``scripts/forge_driver.py``: forge-loop copies the task's
``scripts/forge_driver.py`` verbatim to the workspace root and runs
``python forge_driver.py <args>`` reading only stdout. To have forge-loop use
THIS merged file, place it at ``scripts/forge_driver.py`` (it is a strict
superset of the thin delegator). ``WORKSPACE`` is resolved robustly so it works
whether it runs from the task ``scripts/`` dir (Arena) or the workspace root
(the forge copy).

AUTO-GENERATED by merging task_runner.py + forge_driver.py; do not hand-edit --
regenerate from those two files instead.
"""
from __future__ import annotations

import argparse
import importlib
import importlib.util
import json
import os
import sys
from pathlib import Path


_SESSION_CASES_JSON = r"""{
  "source_day": "2026-07-20",
  "date_field": "session_ended_at",
  "platform": "MI355X/gfx950",
  "framework": "vllm 0.24.0",
  "base_image": "harbor.crusoe.primus-safe.amd.com/sync/vllm-openai-rocm:v0.24.0",
  "selection": "routable_kernels; gpu_pct>=3; session-derived shapes/dtypes",
  "task_name": "mi355x-ci-unified-attention-20260720",
  "operator": "unified_attention",
  "cases": [
    {
      "id": "minimax-k004",
      "model": "MiniMax-M2.7",
      "session_breakdown_id": 88517,
      "kernel_ids": [
        "k004"
      ],
      "gpu_pct": 16.412,
      "params": {
        "q_tokens": 64,
        "num_q_heads": 12,
        "num_kv_heads": 2,
        "head_size": 128,
        "ctx_len": 1024,
        "block_size": 16,
        "q_dtype": "bf16",
        "kv_dtype": "bf16"
      },
      "trace_input_shapes": [
        "(64,12,128) bf16",
        "(64,2,128) bf16",
        "(64,2,128) bf16",
        "(64,12,128) bf16"
      ]
    },
    {
      "id": "gemma-k002",
      "model": "gemma-4-26B-A4B-it",
      "session_breakdown_id": 88502,
      "kernel_ids": [
        "k002"
      ],
      "gpu_pct": 19.643,
      "params": {
        "q_tokens": 64,
        "num_q_heads": 8,
        "num_kv_heads": 4,
        "head_size": 256,
        "ctx_len": 1024,
        "block_size": 16,
        "q_dtype": "bf16",
        "kv_dtype": "bf16"
      },
      "trace_input_shapes": [
        "(64,8,256) bf16",
        "(64,4,256) bf16",
        "(64,4,256) bf16",
        "(64,8,256) bf16"
      ]
    },
    {
      "id": "gemma-k006",
      "model": "gemma-4-26B-A4B-it",
      "session_breakdown_id": 88502,
      "kernel_ids": [
        "k006"
      ],
      "gpu_pct": 3.973,
      "params": {
        "q_tokens": 64,
        "num_q_heads": 8,
        "num_kv_heads": 1,
        "head_size": 512,
        "ctx_len": 1024,
        "block_size": 16,
        "q_dtype": "bf16",
        "kv_dtype": "bf16"
      },
      "trace_input_shapes": [
        "(64,8,512) bf16",
        "(64,1,512) bf16"
      ]
    },
    {
      "id": "gptoss-k020",
      "model": "gpt-oss-120b",
      "session_breakdown_id": 88624,
      "kernel_ids": [
        "k020"
      ],
      "gpu_pct": 7.648,
      "params": {
        "q_tokens": 64,
        "num_q_heads": 8,
        "num_kv_heads": 1,
        "head_size": 64,
        "ctx_len": 1024,
        "block_size": 16,
        "q_dtype": "bf16",
        "kv_dtype": "bf16"
      },
      "trace_input_shapes": [
        "(64,8,64) bf16",
        "(64,1,64) bf16"
      ]
    },
    {
      "id": "mixtral-k031",
      "model": "Mixtral-8x7B-Instruct-v0.1",
      "session_breakdown_id": 88512,
      "kernel_ids": [
        "k031"
      ],
      "gpu_pct": 5.764,
      "params": {
        "q_tokens": 64,
        "num_q_heads": 4,
        "num_kv_heads": 1,
        "head_size": 128,
        "ctx_len": 1024,
        "block_size": 16,
        "q_dtype": "bf16",
        "kv_dtype": "fp8"
      },
      "trace_input_shapes": [
        "(64,4,128) bf16",
        "(64,1,128) bf16",
        "(0,) fp8"
      ]
    }
  ]
}"""


def _resolve_workspace() -> Path:
    """Workspace root whether this file runs from the task ``scripts/`` dir
    (Arena) or from the workspace root (the copy forge-loop makes). Anchored on
    the always-present ``config.yaml``."""
    here = Path(__file__).resolve().parent
    for cand in (here.parent, here):
        if (cand / "config.yaml").is_file():
            return cand
    return here.parent


WORKSPACE = _resolve_workspace()
SPEC = json.loads(_SESSION_CASES_JSON)
OPERATOR = SPEC["operator"]
CASES = SPEC["cases"]


def _configure() -> None:
    for key in ("GPU_ARCHS", "PYTORCH_ROCM_ARCH", "AMDGPU_TARGETS", "GPU_TARGETS"):
        os.environ.setdefault(key, "gfx950")
    os.environ.setdefault("AITER_REBUILD", "2")  # incremental ninja rebuild: keep object cache, recompile only edited sources (avoids full CK re-compile on every agent edit)
    os.environ.setdefault("AITER_JIT_DIR", str(WORKSPACE / "build" / "jit"))
    if (WORKSPACE / "aiter_meta").is_dir():
        os.environ["AITER_META_DIR"] = str(WORKSPACE / "aiter_meta")
        # Blob codegen (gen_instances.py) runs in a subprocess and imports
        # chip_info from aiter/jit/utils; propagate that dir via PYTHONPATH or the
        # codegen fails silently and the build errors with
        # "gemm_..._lookup.h file not found".
        try:
            # Use find_spec (not import) so we do NOT execute/cache the installed
            # aiter before a task that seeds an editable aiter package prepends the
            # workspace to sys.path (importing here would pin the installed copy).
            import importlib.util as _ilu

            _spec = _ilu.find_spec("aiter")
            if _spec and _spec.submodule_search_locations:
                _utils = str(
                    Path(_spec.submodule_search_locations[0]) / "jit" / "utils"
                )
                os.environ["PYTHONPATH"] = (
                    _utils + os.pathsep + os.environ.get("PYTHONPATH", "")
                )
        except Exception:
            pass
    if (WORKSPACE / "aiter").is_dir():
        sys.path.insert(0, str(WORKSPACE))
        os.environ.setdefault(
            "AITER_META_DIR",
            "/usr/local/lib/python3.12/dist-packages/aiter_meta",
        )
        # aiter.utility.aiter_types locates aiter_enum.h relative to the parent of
        # the (seeded) aiter package: <WORKSPACE>/aiter_meta/csrc/include/... . When
        # a task seeds only the aiter package, symlink the installed aiter_meta there
        # so the task runs without needing to seed the whole aiter_meta tree.
        _meta_ws = WORKSPACE / "aiter_meta"
        if not _meta_ws.exists():
            try:
                _installed_meta = Path(os.environ["AITER_META_DIR"])
                if _installed_meta.is_dir():
                    _meta_ws.symlink_to(_installed_meta, target_is_directory=True)
            except Exception:
                pass
    os.chdir(WORKSPACE)


def _measure_cuda_event_fallback(fn, repetition):
    import time
    import torch

    times_ms = []
    for _ in range(max(1, int(repetition))):
        if torch.cuda.is_available():
            torch.cuda.synchronize()
            start_event = torch.cuda.Event(enable_timing=True)
            end_event = torch.cuda.Event(enable_timing=True)
            start_event.record()
            fn()
            end_event.record()
            torch.cuda.synchronize()
            times_ms.append(start_event.elapsed_time(end_event))
        else:
            start = time.perf_counter()
            fn()
            times_ms.append((time.perf_counter() - start) * 1000.0)
    return times_ms


def _benchmark_cuda_graph_or_events(
    fn,
    warmup=5,
    repetition=30,
    target_ms=1.0,
    max_graph_repeats=200,
    use_cuda_graph=True,
    **_,
):
    import torch

    for _ in range(max(0, int(warmup))):
        fn()
    if torch.cuda.is_available():
        torch.cuda.synchronize()

    metadata = {
        "benchmark_target_ms": float(target_ms),
        "benchmark_samples": int(repetition),
        "benchmark_max_repeats": int(max_graph_repeats),
    }
    if not torch.cuda.is_available() or not use_cuda_graph:
        times = _measure_cuda_event_fallback(fn, repetition)
        metadata.update(
            benchmark_method=(
                "cpu_timer_fallback"
                if not torch.cuda.is_available()
                else "cuda_event_fallback"
            ),
            benchmark_effective_repeats=int(repetition),
            benchmark_fallback_reason=(
                "cuda_unavailable"
                if not torch.cuda.is_available()
                else "cuda_graph_disabled"
            ),
        )
        return sum(times) / len(times), metadata

    try:
        stream = torch.cuda.Stream()
        stream.wait_stream(torch.cuda.current_stream())
        with torch.cuda.stream(stream):
            estimate_graph = torch.cuda.CUDAGraph()
            with torch.cuda.graph(estimate_graph):
                for _ in range(3):
                    fn()
            torch.cuda.synchronize()

            start_event = torch.cuda.Event(enable_timing=True)
            end_event = torch.cuda.Event(enable_timing=True)
            start_event.record(stream)
            estimate_graph.replay()
            end_event.record(stream)
            torch.cuda.synchronize()
            estimate_ms = start_event.elapsed_time(end_event) / 3
            repeats = min(
                max_graph_repeats,
                max(1, int(target_ms / max(estimate_ms, 1e-9))),
            )

            graph = torch.cuda.CUDAGraph()
            with torch.cuda.graph(graph):
                for _ in range(repeats):
                    fn()
            torch.cuda.synchronize()

            times = []
            for _ in range(max(1, int(repetition))):
                start_event = torch.cuda.Event(enable_timing=True)
                end_event = torch.cuda.Event(enable_timing=True)
                start_event.record(stream)
                graph.replay()
                end_event.record(stream)
                torch.cuda.synchronize()
                times.append(start_event.elapsed_time(end_event) / repeats)

        mean_ms = sum(times) / len(times)
        if mean_ms < 1e-4:
            raise RuntimeError("empty_cuda_graph_capture")
        metadata.update(
            benchmark_method="cuda_graph",
            benchmark_effective_repeats=int(repeats),
        )
        return mean_ms, metadata
    except Exception as exc:
        try:
            torch.cuda.synchronize()
        except Exception:
            pass
        times = _measure_cuda_event_fallback(fn, repetition)
        metadata.update(
            benchmark_method="cuda_event_fallback",
            benchmark_effective_repeats=int(repetition),
            benchmark_fallback_reason=(
                f"cuda_graph_failed: {type(exc).__name__}: {str(exc)[:160]}"
            ),
        )
        return sum(times) / len(times), metadata


def _write_report(rows: list[dict]) -> None:
    report_dir = WORKSPACE / "build"
    report_dir.mkdir(parents=True, exist_ok=True)
    (report_dir / "performance_report.json").write_text(json.dumps(rows, indent=2))


def _torch():
    import torch

    if not torch.cuda.is_available():
        raise RuntimeError("ROCm GPU is required")
    return torch


def _make_attention(case: dict, correctness: bool = False) -> dict:
    torch = _torch()
    params = dict(case["params"])
    ctx_len = min(params["ctx_len"], 128) if correctness else params["ctx_len"]
    num_seqs = params["q_tokens"]
    num_q_heads = params["num_q_heads"]
    num_kv_heads = params["num_kv_heads"]
    head_size = params["head_size"]
    block_size = params["block_size"]
    pages_per_seq = (ctx_len + block_size - 1) // block_size
    num_blocks = num_seqs * pages_per_seq

    torch.manual_seed(7)
    query = torch.randn(
        (num_seqs, num_q_heads, head_size),
        device="cuda",
        dtype=torch.bfloat16,
    )
    kv = torch.randn(
        (num_blocks, block_size, num_kv_heads, head_size),
        device="cuda",
        dtype=torch.bfloat16,
    )
    if params["kv_dtype"] == "fp8":
        key = kv.to(torch.float8_e4m3fn)
        value = (kv * 0.7).to(torch.float8_e4m3fn)
    else:
        key = kv
        value = kv * 0.7

    output = torch.empty_like(query)
    cu_seqlens_q = torch.arange(num_seqs + 1, device="cuda", dtype=torch.int32)
    seqused_k = torch.full(
        (num_seqs,), ctx_len, device="cuda", dtype=torch.int32
    )
    block_table = torch.arange(
        num_blocks, device="cuda", dtype=torch.int32
    ).view(num_seqs, pages_per_seq)
    one = torch.ones(1, device="cuda", dtype=torch.float32)
    return {
        "cfg": case,
        "query": query,
        "key": key,
        "value": value,
        "output": output,
        "cu_seqlens_q": cu_seqlens_q,
        "seqused_k": seqused_k,
        "block_table": block_table,
        "ctx_len": ctx_len,
        "scale": head_size**-0.5,
        "one": one,
    }


def _run_attention(inputs: dict):
    from aiter.ops.triton.attention.unified_attention import unified_attention

    unified_attention(
        inputs["query"],
        inputs["key"],
        inputs["value"],
        inputs["output"],
        inputs["cu_seqlens_q"],
        1,
        inputs["seqused_k"],
        inputs["ctx_len"],
        inputs["scale"],
        True,
        (-1, -1),
        inputs["block_table"],
        0.0,
        inputs["one"],
        inputs["one"],
        inputs["one"],
    )
    return inputs["output"]


def _attention_reference(inputs: dict):
    torch = _torch()
    query = inputs["query"].float()
    key = inputs["key"].float()
    value = inputs["value"].float()
    outputs = []
    for seq_idx in range(query.shape[0]):
        block_ids = inputs["block_table"][seq_idx]
        key_seq = key[block_ids].reshape(-1, key.shape[2], key.shape[3])
        value_seq = value[block_ids].reshape(-1, value.shape[2], value.shape[3])
        key_seq = key_seq[: inputs["ctx_len"]]
        value_seq = value_seq[: inputs["ctx_len"]]
        ratio = query.shape[1] // key_seq.shape[1]
        key_seq = key_seq.repeat_interleave(ratio, dim=1)
        value_seq = value_seq.repeat_interleave(ratio, dim=1)
        scores = (
            torch.einsum("hd,khd->hk", query[seq_idx], key_seq)
            * inputs["scale"]
        )
        probs = torch.softmax(scores, dim=-1)
        outputs.append(torch.einsum("hk,khd->hd", probs, value_seq))
    return torch.stack(outputs).to(inputs["output"].dtype)


def run_compile() -> None:
    inputs = _make(CASES[0], correctness=True)
    _run(inputs)
    _torch().cuda.synchronize()
    print(f"{OPERATOR} compile smoke: PASS")


def run_performance() -> None:
    rows = []
    for case in CASES:
        inputs = _make(case, correctness=False)
        _run(inputs)
        _torch().cuda.synchronize()
        execution_time_ms, bench_meta = _benchmark_cuda_graph_or_events(
            lambda: _run(inputs),
            warmup=3,
            repetition=20,
            target_ms=1.0,
            max_graph_repeats=100,
        )
        metadata = {
            **case["params"],
            "model": case["model"],
            "session_breakdown_id": case["session_breakdown_id"],
            "kernel_ids": case["kernel_ids"],
            "gpu_pct": case["gpu_pct"],
            "benchmark_method": bench_meta.get("benchmark_method"),
        }
        metadata.update(
            {
                key: value
                for key, value in bench_meta.items()
                if key.startswith("benchmark_")
            }
        )
        row = {
            "test_case_id": case["id"],
            "shape": case["trace_input_shapes"],
            "execution_time_ms": execution_time_ms,
            "metadata": metadata,
        }
        rows.append(row)
        print(
            case["id"],
            f"{execution_time_ms:.6f} ms",
            bench_meta.get("benchmark_method"),
            bench_meta.get("benchmark_fallback_reason", ""),
        )
    _write_report(rows)


def _make(case: dict, correctness: bool = False) -> dict:
    return _make_attention(case, correctness)


def _run(inputs: dict):
    return _run_attention(inputs)


def run_correctness() -> None:
    torch = _torch()
    for case in CASES:
        inputs = _make(case, correctness=True)
        got = _run(inputs)
        torch.cuda.synchronize()
        torch.testing.assert_close(
            got, _attention_reference(inputs), atol=0.08, rtol=0.08
        )
        print("correctness PASS", case["id"])


import argparse
import importlib.util
import json
import sys
from pathlib import Path



def _import_task_runner():
    """This merged file inlines task_runner above; return this module."""
    return sys.modules[__name__], Path(__file__).resolve().parent

def _report_path(tr) -> Path:
    return Path(tr.WORKSPACE) / "build" / "performance_report.json"


def _run_correctness(tr) -> int:
    """Delegate to the task's own per-operator correctness; map to allclose."""
    ok = True
    try:
        tr.run_correctness()  # asserts / raises on any failing case
    except Exception as exc:  # noqa: BLE001 - any failure is a correctness fail
        ok = False
        print(f"# correctness failed: {type(exc).__name__}: {str(exc)[:300]}")
    print(f"allclose: {ok}")
    return 0


def _run_bench(tr) -> int:
    """Delegate to the task's graph-timed run_performance(); expose per-case ms."""
    tr.run_performance()  # writes build/performance_report.json, graph-timed
    rows = json.loads(_report_path(tr).read_text())
    times = []
    for row in rows:
        cid = str(row.get("test_case_id", "")).replace(" ", "_")
        ms = row.get("execution_time_ms")
        if ms is None or float(ms) <= 0:
            continue
        times.append(float(ms))
        print(f"case_ms: {cid} {float(ms):.6f}")
    if not times:
        print("error: run_performance produced no usable timing", file=sys.stderr)
        return 1
    print(f"mean_ms: {sum(times) / len(times):.6f}")
    return 0


def _pick_profile_case(tr, case_id: str) -> dict:
    cases = {c["id"]: c for c in tr.CASES}
    if case_id and case_id in cases:
        return cases[case_id]
    # Fallback (forge normally passes --profile-case, derived from case_ms): use
    # the slowest case from a prior perf report if present, else the last case
    # (session cases are ordered decode->prefill, i.e. smallest->largest).
    rp = _report_path(tr)
    if rp.is_file():
        try:
            rows = json.loads(rp.read_text())
            best = max(rows, key=lambda r: float(r.get("execution_time_ms") or 0))
            if best.get("test_case_id") in cases:
                return cases[best["test_case_id"]]
        except Exception:  # noqa: BLE001 - best-effort fallback
            pass
    return tr.CASES[-1]


def _run_profile(tr, case_id: str) -> int:
    torch = tr._torch()
    case = _pick_profile_case(tr, case_id)
    inputs = tr._make(case, correctness=False)
    for _ in range(5):          # settle Triton JIT / autotune selection
        tr._run(inputs)
    torch.cuda.synchronize()
    for _ in range(3):          # profiled launches (profiler replays per group)
        tr._run(inputs)
    torch.cuda.synchronize()
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Generic image_kernel forge driver")
    parser.add_argument("--shape", default="default")  # task owns its shapes
    parser.add_argument("--mode", default="full")       # all modes -> task correctness
    parser.add_argument("--bench-mode", action="store_true")
    parser.add_argument("--profile-run", action="store_true")
    parser.add_argument("--profile-case", default="")
    parser.add_argument("--warmup", type=int, default=10)
    parser.add_argument("--iters", type=int, default=30)
    args, _unknown = parser.parse_known_args()

    tr, _scripts_dir = _import_task_runner()
    tr._configure()  # arch env + make the seeded (agent-editable) repo importable

    import torch
    if not torch.cuda.is_available():
        print("error: ROCm GPU (gfx950) is required (torch.cuda.is_available() is False)",
              file=sys.stderr)
        return 1

    if args.profile_run:
        return _run_profile(tr, args.profile_case)
    if args.bench_mode:
        return _run_bench(tr)
    return _run_correctness(tr)


if __name__ == "__main__":
    sys.exit(main())
